sudo: required
dist: trusty
branches:
  only:
  - master
  - develop
matrix:
  include:
    - language: node_js
      node_js:  10
      before_install:
        - cd ./microservices/purple
      install:
        - npm install
      script:
        - npm run build
        - npm start