#!/bin/bash
echo 'Adding DOCKER REPOSITORIES'
sudo yum install -y yum-utils device-mapper-persistent-data lvm2
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
echo 'INSTALLING DOCKER FROM REPOSITORIES'
sudo yum install docker-ce docker-ce-cli containerd.io
echo 'STARTING DOCKER'
sudo systemctl start docker
sudo systemctl enable docker.service